# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import sys

from bro.base.args import run_cli


def bro_artifact():
  return run_cli('bro.artifact', sys.argv)


def bro_base_credentials():
  return run_cli('bro.base.credentials', sys.argv)


def bro_base_time_util():
  return run_cli('bro.base.time_util', sys.argv)


def bro_broker_broxy():
  return run_cli('bro.broker.broxy', sys.argv)


def bro_broker_cli():
  return run_cli('bro.broker.cli', sys.argv)


def bro_llm_usage():
  return run_cli('bro.llm.usage', sys.argv)


def bro_runtime_mcp_server():
  return run_cli('bro.runtime.mcp_server', sys.argv)


def bro_shell():
  return run_cli('bro.shell', sys.argv)


def bro_summon():
  return run_cli('bro.summon', sys.argv)


def bro_trails_admin():
  return run_cli('bro.trails.admin', sys.argv)


def bro_trails_rewind():
  return run_cli('bro.trails.rewind', sys.argv)


def bro_trails_server_server():
  return run_cli('bro.trails.server.server', sys.argv)
