# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import importlib
import sys


def _run(module):
  return importlib.import_module(module).main(sys.argv)


def bro_base_credentials():
  return _run('bro.base.credentials')


def bro_base_time_util():
  return _run('bro.base.time_util')


def bro_broker_broxy():
  return _run('bro.broker.broxy')


def bro_broker_cli():
  return _run('bro.broker.cli')


def bro_extra_github_poll_pr():
  return _run('bro.extra.github.poll_pr')


def bro_llm_usage():
  return _run('bro.llm.usage')


def bro_native_llm():
  return _run('bro.native.llm')


def bro_run():
  return _run('bro.run')


def bro_runtime_mcp_server():
  return _run('bro.runtime.mcp_server')


def bro_shell():
  return _run('bro.shell')


def bro_summon():
  return _run('bro.summon')


def bro_trails_record_claude():
  return _run('bro.trails.record.claude')


def bro_trails_rewind():
  return _run('bro.trails.rewind')


def bro_trails_server_server():
  return _run('bro.trails.server.server')


def bro_workflow_commit_footer():
  return _run('bro.workflow.commit_footer')


def bro_workflow_fold_branch():
  return _run('bro.workflow.fold_branch')


def bro_workflow_land_pr():
  return _run('bro.workflow.land_pr')
