# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import importlib
import sys


def _run(module):
  return importlib.import_module(module).main(sys.argv)


def bro_dev_git_golc():
  return _run('bro.dev.git_golc')


def bro_dev_install():
  return _run('bro.dev.install')


def bro_dev_sync_scripts():
  return _run('bro.dev.sync_scripts')


def bro_dev_usage_report():
  return _run('bro.dev.usage_report')


def bros_analyst_scripts_trails_usage():
  return _run('bros.analyst.scripts.trails_usage')
