# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import sys

from bro.base.args import run_cli


def bro_dev_git_golc():
  return run_cli('bro.dev.git_golc', sys.argv)


def bro_dev_install():
  return run_cli('bro.dev.install', sys.argv)


def bro_dev_markdown_policy():
  return run_cli('bro.dev.markdown_policy', sys.argv)


def bro_dev_sync_scripts():
  return run_cli('bro.dev.sync_scripts', sys.argv)


def bro_dev_usage_report():
  return run_cli('bro.dev.usage_report', sys.argv)


def bro_extra_github_poll_pr():
  return run_cli('bro.extra.github.poll_pr', sys.argv)


def bro_extra_github_pr_state():
  return run_cli('bro.extra.github.pr_state', sys.argv)


def bro_workflow_commit_footer():
  return run_cli('bro.workflow.commit_footer', sys.argv)


def bro_workflow_fold_branch():
  return run_cli('bro.workflow.fold_branch', sys.argv)


def bro_workflow_land_pr():
  return run_cli('bro.workflow.land_pr', sys.argv)


def bros_analyst_scripts_trails_usage():
  return run_cli('bros.analyst.scripts.trails_usage', sys.argv)
