# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import importlib
import sys


def _run(module):
  return importlib.import_module(module).main(sys.argv)


def bro_local_benchmark_job():
  return _run('bro.local.benchmark_job')


def bro_local_run_tests():
  return _run('bro.local.run_tests')
