# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import sys

from bro.base.args import run_cli


def bro_local_benchmark_job():
  return run_cli('bro.local.benchmark_job', sys.argv)


def bro_local_benchmark_run():
  return run_cli('bro.local.benchmark_run', sys.argv)


def bro_local_run_tests():
  return run_cli('bro.local.run_tests', sys.argv)
