"""Typed, renderer-neutral presentation of recorded and live trail activity."""

from bro.trails.display.blocks import (
  Append,
  BlockItem,
  BlockKind,
  BlockOperation,
  PresentationBlock,
  Remove,
  Renderer,
  RendererCapabilities,
  StyleRole,
  Update,
)
from bro.trails.display.config import (
  PRESETS,
  Appearance,
  AttributePredicate,
  ColorMode,
  ContentLimits,
  DisplayConfig,
  Labels,
  Layout,
  OutputRoute,
  OutputRoutes,
  PresetName,
  RecordFilter,
  TimestampPolicy,
  Verbosity,
  preset,
)
from bro.trails.display.core import DisplayDataError, DisplaySession, sanitize_text
from bro.trails.display.live import LiveDisplayObserver
from bro.trails.display.recorded import RecordedAdapter
from bro.trails.display.records import (
  ALL_RECORD_KINDS,
  CONVERSATION_RECORD_KINDS,
  STRUCTURAL_RECORD_KINDS,
  SURFACE_RECORD_KINDS,
  AssistantText,
  DisplayRecord,
  Error,
  HarnessEvent,
  InlineStepBody,
  InterimAssistantText,
  LaunchContextEntry,
  LineageNode,
  LiveSource,
  LLMCall,
  NativeStep,
  Notice,
  Origin,
  Reasoning,
  Record,
  RecordedSource,
  RecordKind,
  RecordSource,
  SegmentBoundary,
  SpilledStepBody,
  StepBody,
  SystemPrompt,
  ToolCall,
  ToolResult,
  TrailListRow,
  TrailMetadata,
  TransientActivity,
  UserInput,
)
from bro.trails.display.terminal import RetainedRenderer, StreamRenderer, color_enabled
