# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import importlib
import sys


def _run(module):
  return importlib.import_module(module).main(sys.argv)


def ride_ask():
  return _run('ride.ask')


def ride_call():
  return _run('ride.call')


def ride_claude_print_anthropic_key():
  return _run('ride.claude.print_anthropic_key')


def ride_claude_statusline():
  return _run('ride.claude.statusline')


def ride_claude_watch_guard():
  return _run('ride.claude.watch_guard')


def ride_cli():
  return _run('ride.cli')


def ride_dive_in():
  return _run('ride.dive_in')
