# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import sys

from bro.base.args import run_cli


def ride_ask():
  return run_cli('ride.ask', sys.argv)


def ride_call():
  return run_cli('ride.call', sys.argv)


def ride_claude_command_gate():
  return run_cli('ride.claude.command_gate', sys.argv)


def ride_claude_read_gate():
  return run_cli('ride.claude.read_gate', sys.argv)


def ride_claude_statusline():
  return run_cli('ride.claude.statusline', sys.argv)


def ride_claude_trail_recorder():
  return run_cli('ride.claude.trail_recorder', sys.argv)


def ride_claude_watch_waiter():
  return run_cli('ride.claude.watch_waiter', sys.argv)


def ride_cli():
  return run_cli('ride.cli', sys.argv)


def ride_dive_in():
  return run_cli('ride.dive_in', sys.argv)


def ride_do_ride():
  return run_cli('ride.do_ride', sys.argv)
