# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import sys

from bro.base.args import run_cli


def bro_oops_assets():
  return run_cli('bro.oops.assets', sys.argv)
