# generated by `sync-scripts`; do not edit.
# console scripts import these zero-argument shims, which feed sys.argv to
# each CLI's main(argv) -- the single place the process reads the global argv.
import importlib
import sys


def _run(module):
  return importlib.import_module(module).main(sys.argv)


def bro_oops_assets():
  return _run('bro.oops.assets')
